/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXcmPrecompile,
  IXcmPrecompileInterface,
} from "../../../contracts/interfaces/IXcmPrecompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "weighMessage",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "refTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "proofSize",
            type: "uint64",
          },
        ],
        internalType: "struct IXcmPrecompile.Weight",
        name: "weight",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "refTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "proofSize",
            type: "uint64",
          },
        ],
        internalType: "struct IXcmPrecompile.Weight",
        name: "weight",
        type: "tuple",
      },
    ],
    name: "xcmExecute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "destination",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "xcmSend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXcmPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): IXcmPrecompileInterface {
    return new Interface(_abi) as IXcmPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXcmPrecompile {
    return new Contract(address, _abi, runner) as unknown as IXcmPrecompile;
  }
}
