/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ILiquidityAdapter {
  export type AdapterInfoStruct = {
    name: string;
    adapterAddress: AddressLike;
    isActive: boolean;
    tvl: BigNumberish;
    fee: BigNumberish;
    minSwapAmount: BigNumberish;
    maxSwapAmount: BigNumberish;
    supportedTokens: AddressLike[];
  };

  export type AdapterInfoStructOutput = [
    name: string,
    adapterAddress: string,
    isActive: boolean,
    tvl: bigint,
    fee: bigint,
    minSwapAmount: bigint,
    maxSwapAmount: bigint,
    supportedTokens: string[]
  ] & {
    name: string;
    adapterAddress: string;
    isActive: boolean;
    tvl: bigint;
    fee: bigint;
    minSwapAmount: bigint;
    maxSwapAmount: bigint;
    supportedTokens: string[];
  };
}

export interface UniswapV2AdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADAPTER_ADMIN"
      | "DEFAULT_ADMIN_ROLE"
      | "FEE_MANAGER"
      | "LIQUIDITY_PROVIDER"
      | "MAX_FEE"
      | "addLiquidity(address,uint256,bytes)"
      | "addLiquidity(address,address,uint256,uint256,uint256,uint256,address)"
      | "emergencyWithdraw"
      | "fee"
      | "feeCollector"
      | "getAdapterInfo"
      | "getAmountOut"
      | "getFactory"
      | "getFee"
      | "getPairInfo"
      | "getReserves"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initializePair"
      | "isActive"
      | "isTokenSupported"
      | "maxSwapAmount"
      | "minSwapAmount"
      | "name"
      | "removeLiquidity(address,uint256,bytes)"
      | "removeLiquidity(address,address,uint256,uint256,uint256,address)"
      | "removePair"
      | "renounceRole"
      | "revokeRole"
      | "setActive"
      | "setFactory"
      | "setFee"
      | "setFeeCollector"
      | "setSwapLimits"
      | "skimPair"
      | "supportsInterface"
      | "swapExactTokensForTokens"
      | "syncAllPairs"
      | "syncPair"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterActivated"
      | "AdapterDeactivated"
      | "FeeCollectorUpdated"
      | "LiquidityAdded"
      | "LiquidityProvided"
      | "LiquidityRemoved"
      | "PairInitialized"
      | "PairSynced"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SwapExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADAPTER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDITY_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addLiquidity(address,uint256,bytes)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity(address,address,uint256,uint256,uint256,uint256,address)",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAdapterInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPairInfo",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSwapAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minSwapAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity(address,uint256,bytes)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity(address,address,uint256,uint256,uint256,address)",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removePair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setActive", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "skimPair",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokens",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "syncAllPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "syncPair",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADAPTER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDITY_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity(address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity(address,address,uint256,uint256,uint256,uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdapterInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPairInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSwapAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minSwapAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity(address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity(address,address,uint256,uint256,uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removePair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skimPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncAllPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "syncPair", data: BytesLike): Result;
}

export namespace AdapterActivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdapterDeactivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [
    oldCollector: AddressLike,
    newCollector: AddressLike
  ];
  export type OutputTuple = [oldCollector: string, newCollector: string];
  export interface OutputObject {
    oldCollector: string;
    newCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    newReserve: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, newReserve: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    newReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityProvidedEvent {
  export type InputTuple = [
    provider: AddressLike,
    tokenA: AddressLike,
    tokenB: AddressLike,
    amountA: BigNumberish,
    amountB: BigNumberish,
    liquidity: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    tokenA: string,
    tokenB: string,
    amountA: bigint,
    amountB: bigint,
    liquidity: bigint
  ];
  export interface OutputObject {
    provider: string;
    tokenA: string;
    tokenB: string;
    amountA: bigint;
    amountB: bigint;
    liquidity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    newReserve: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, newReserve: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    newReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairInitializedEvent {
  export type InputTuple = [
    tokenA: AddressLike,
    tokenB: AddressLike,
    pair: AddressLike
  ];
  export type OutputTuple = [tokenA: string, tokenB: string, pair: string];
  export interface OutputObject {
    tokenA: string;
    tokenB: string;
    pair: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairSyncedEvent {
  export type InputTuple = [
    tokenA: AddressLike,
    tokenB: AddressLike,
    reserve0: BigNumberish,
    reserve1: BigNumberish
  ];
  export type OutputTuple = [
    tokenA: string,
    tokenB: string,
    reserve0: bigint,
    reserve1: bigint
  ];
  export interface OutputObject {
    tokenA: string;
    tokenB: string;
    reserve0: bigint;
    reserve1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    adapter: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    adapter: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint,
    recipient: string
  ];
  export interface OutputObject {
    adapter: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniswapV2Adapter extends BaseContract {
  connect(runner?: ContractRunner | null): UniswapV2Adapter;
  waitForDeployment(): Promise<this>;

  interface: UniswapV2AdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADAPTER_ADMIN: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FEE_MANAGER: TypedContractMethod<[], [string], "view">;

  LIQUIDITY_PROVIDER: TypedContractMethod<[], [string], "view">;

  MAX_FEE: TypedContractMethod<[], [bigint], "view">;

  "addLiquidity(address,uint256,bytes)": TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  "addLiquidity(address,address,uint256,uint256,uint256,uint256,address)": TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      amountADesired: BigNumberish,
      amountBDesired: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: AddressLike
    ],
    [
      [bigint, bigint, bigint] & {
        amountA: bigint;
        amountB: bigint;
        liquidity: bigint;
      }
    ],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fee: TypedContractMethod<[], [bigint], "view">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getAdapterInfo: TypedContractMethod<
    [],
    [ILiquidityAdapter.AdapterInfoStructOutput],
    "view"
  >;

  getAmountOut: TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        feePercent: bigint;
        priceImpact: bigint;
      }
    ],
    "view"
  >;

  getFactory: TypedContractMethod<[], [string], "view">;

  getFee: TypedContractMethod<[], [bigint], "view">;

  getPairInfo: TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [[string, bigint, bigint, bigint, bigint]],
    "view"
  >;

  getReserves: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initializePair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [void],
    "nonpayable"
  >;

  isActive: TypedContractMethod<[], [boolean], "view">;

  isTokenSupported: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  maxSwapAmount: TypedContractMethod<[], [bigint], "view">;

  minSwapAmount: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  "removeLiquidity(address,uint256,bytes)": TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  "removeLiquidity(address,address,uint256,uint256,uint256,address)": TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      liquidity: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: AddressLike
    ],
    [[bigint, bigint] & { amountA: bigint; amountB: bigint }],
    "nonpayable"
  >;

  removePair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setActive: TypedContractMethod<[a: boolean], [void], "nonpayable">;

  setFactory: TypedContractMethod<[f: AddressLike], [void], "nonpayable">;

  setFee: TypedContractMethod<[f: BigNumberish], [void], "nonpayable">;

  setFeeCollector: TypedContractMethod<[c: AddressLike], [void], "nonpayable">;

  setSwapLimits: TypedContractMethod<
    [mn: BigNumberish, mx: BigNumberish],
    [void],
    "nonpayable"
  >;

  skimPair: TypedContractMethod<
    [a: AddressLike, b: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  swapExactTokensForTokens: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      recipient: AddressLike,
      arg5: BytesLike
    ],
    [[bigint, bigint] & { amountOut: bigint; feeAmount: bigint }],
    "nonpayable"
  >;

  syncAllPairs: TypedContractMethod<[], [void], "nonpayable">;

  syncPair: TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADAPTER_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_MANAGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUIDITY_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity(address,uint256,bytes)"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLiquidity(address,address,uint256,uint256,uint256,uint256,address)"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      amountADesired: BigNumberish,
      amountBDesired: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: AddressLike
    ],
    [
      [bigint, bigint, bigint] & {
        amountA: bigint;
        amountB: bigint;
        liquidity: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAdapterInfo"
  ): TypedContractMethod<
    [],
    [ILiquidityAdapter.AdapterInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        feePercent: bigint;
        priceImpact: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPairInfo"
  ): TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [[string, bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<[token: AddressLike], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializePair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxSwapAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minSwapAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity(address,uint256,bytes)"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity(address,address,uint256,uint256,uint256,address)"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      liquidity: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: AddressLike
    ],
    [[bigint, bigint] & { amountA: bigint; amountB: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removePair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<[a: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[f: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[f: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[c: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSwapLimits"
  ): TypedContractMethod<
    [mn: BigNumberish, mx: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "skimPair"
  ): TypedContractMethod<
    [a: AddressLike, b: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapExactTokensForTokens"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      recipient: AddressLike,
      arg5: BytesLike
    ],
    [[bigint, bigint] & { amountOut: bigint; feeAmount: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "syncAllPairs"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "syncPair"
  ): TypedContractMethod<
    [a: AddressLike, b: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdapterActivated"
  ): TypedContractEvent<
    AdapterActivatedEvent.InputTuple,
    AdapterActivatedEvent.OutputTuple,
    AdapterActivatedEvent.OutputObject
  >;
  getEvent(
    key: "AdapterDeactivated"
  ): TypedContractEvent<
    AdapterDeactivatedEvent.InputTuple,
    AdapterDeactivatedEvent.OutputTuple,
    AdapterDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityProvided"
  ): TypedContractEvent<
    LiquidityProvidedEvent.InputTuple,
    LiquidityProvidedEvent.OutputTuple,
    LiquidityProvidedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PairInitialized"
  ): TypedContractEvent<
    PairInitializedEvent.InputTuple,
    PairInitializedEvent.OutputTuple,
    PairInitializedEvent.OutputObject
  >;
  getEvent(
    key: "PairSynced"
  ): TypedContractEvent<
    PairSyncedEvent.InputTuple,
    PairSyncedEvent.OutputTuple,
    PairSyncedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;

  filters: {
    "AdapterActivated(address)": TypedContractEvent<
      AdapterActivatedEvent.InputTuple,
      AdapterActivatedEvent.OutputTuple,
      AdapterActivatedEvent.OutputObject
    >;
    AdapterActivated: TypedContractEvent<
      AdapterActivatedEvent.InputTuple,
      AdapterActivatedEvent.OutputTuple,
      AdapterActivatedEvent.OutputObject
    >;

    "AdapterDeactivated(address)": TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;
    AdapterDeactivated: TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;

    "FeeCollectorUpdated(address,address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityProvided(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityProvidedEvent.InputTuple,
      LiquidityProvidedEvent.OutputTuple,
      LiquidityProvidedEvent.OutputObject
    >;
    LiquidityProvided: TypedContractEvent<
      LiquidityProvidedEvent.InputTuple,
      LiquidityProvidedEvent.OutputTuple,
      LiquidityProvidedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "PairInitialized(address,address,address)": TypedContractEvent<
      PairInitializedEvent.InputTuple,
      PairInitializedEvent.OutputTuple,
      PairInitializedEvent.OutputObject
    >;
    PairInitialized: TypedContractEvent<
      PairInitializedEvent.InputTuple,
      PairInitializedEvent.OutputTuple,
      PairInitializedEvent.OutputObject
    >;

    "PairSynced(address,address,uint112,uint112)": TypedContractEvent<
      PairSyncedEvent.InputTuple,
      PairSyncedEvent.OutputTuple,
      PairSyncedEvent.OutputObject
    >;
    PairSynced: TypedContractEvent<
      PairSyncedEvent.InputTuple,
      PairSyncedEvent.OutputTuple,
      PairSyncedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SwapExecuted(address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
  };
}
