/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapV2AdapterSol from "./UniswapV2Adapter.sol";
export type { uniswapV2AdapterSol };
export type { ParachainAdapter } from "./ParachainAdapter";
