/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ILiquidityAdapter {
  export type AdapterInfoStruct = {
    name: string;
    adapterAddress: AddressLike;
    isActive: boolean;
    tvl: BigNumberish;
    fee: BigNumberish;
    minSwapAmount: BigNumberish;
    maxSwapAmount: BigNumberish;
    supportedTokens: AddressLike[];
  };

  export type AdapterInfoStructOutput = [
    name: string,
    adapterAddress: string,
    isActive: boolean,
    tvl: bigint,
    fee: bigint,
    minSwapAmount: bigint,
    maxSwapAmount: bigint,
    supportedTokens: string[]
  ] & {
    name: string;
    adapterAddress: string;
    isActive: boolean;
    tvl: bigint;
    fee: bigint;
    minSwapAmount: bigint;
    maxSwapAmount: bigint;
    supportedTokens: string[];
  };
}

export declare namespace ParachainAdapter {
  export type ParachainConfigStruct = {
    parachainId: BigNumberish;
    name: string;
    bridgeFee: BigNumberish;
    minTransfer: BigNumberish;
    maxTransfer: BigNumberish;
    timeout: BigNumberish;
    isActive: boolean;
  };

  export type ParachainConfigStructOutput = [
    parachainId: bigint,
    name: string,
    bridgeFee: bigint,
    minTransfer: bigint,
    maxTransfer: bigint,
    timeout: bigint,
    isActive: boolean
  ] & {
    parachainId: bigint;
    name: string;
    bridgeFee: bigint;
    minTransfer: bigint;
    maxTransfer: bigint;
    timeout: bigint;
    isActive: boolean;
  };

  export type TokenMappingStruct = {
    erc20Address: AddressLike;
    parachainAssetId: BytesLike;
    decimals: BigNumberish;
    minTransfer: BigNumberish;
    maxTransfer: BigNumberish;
    isNative: boolean;
    isActive: boolean;
  };

  export type TokenMappingStructOutput = [
    erc20Address: string,
    parachainAssetId: string,
    decimals: bigint,
    minTransfer: bigint,
    maxTransfer: bigint,
    isNative: boolean,
    isActive: boolean
  ] & {
    erc20Address: string;
    parachainAssetId: string;
    decimals: bigint;
    minTransfer: bigint;
    maxTransfer: bigint;
    isNative: boolean;
    isActive: boolean;
  };
}

export interface ParachainAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADAPTER_ADMIN"
      | "BRIDGE_OPERATOR"
      | "DEFAULT_ADMIN_ROLE"
      | "addLiquidity"
      | "configureParachain"
      | "getAdapterInfo"
      | "getAmountOut"
      | "getAssetId"
      | "getParachainConfig"
      | "getParachainTokens"
      | "getReserves"
      | "getRoleAdmin"
      | "getSupportedParachains"
      | "getTokenMapping"
      | "grantRole"
      | "hasRole"
      | "isTokenSupported"
      | "mapToken"
      | "removeLiquidity"
      | "renounceRole"
      | "revokeRole"
      | "setActive"
      | "setFee"
      | "setSwapLimits"
      | "setXCMExecutor"
      | "supportsInterface"
      | "swapExactTokensForTokens"
      | "unmapToken"
      | "updateParachainConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterActivated"
      | "AdapterDeactivated"
      | "BridgeExecuted"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "ParachainConfigured"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SwapExecuted"
      | "TokenMapped"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADAPTER_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BRIDGE_OPERATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "configureParachain",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdapterInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetId",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParachainConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParachainTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedParachains",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenMapping",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mapToken",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setActive", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setXCMExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokens",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unmapToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateParachainConfig",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADAPTER_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BRIDGE_OPERATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureParachain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdapterInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAssetId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParachainConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParachainTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedParachains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mapToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSwapLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setXCMExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unmapToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateParachainConfig",
    data: BytesLike
  ): Result;
}

export namespace AdapterActivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdapterDeactivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeExecutedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    parachainId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    parachainId: bigint,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    messageId: string;
    parachainId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    newReserve: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, newReserve: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    newReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    newReserve: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, newReserve: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    newReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParachainConfiguredEvent {
  export type InputTuple = [
    parachainId: BigNumberish,
    name: string,
    bridgeFee: BigNumberish
  ];
  export type OutputTuple = [
    parachainId: bigint,
    name: string,
    bridgeFee: bigint
  ];
  export interface OutputObject {
    parachainId: bigint;
    name: string;
    bridgeFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    adapter: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    adapter: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint,
    recipient: string
  ];
  export interface OutputObject {
    adapter: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenMappedEvent {
  export type InputTuple = [
    token: AddressLike,
    parachainId: BigNumberish,
    assetId: BytesLike
  ];
  export type OutputTuple = [
    token: string,
    parachainId: bigint,
    assetId: string
  ];
  export interface OutputObject {
    token: string;
    parachainId: bigint;
    assetId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ParachainAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): ParachainAdapter;
  waitForDeployment(): Promise<this>;

  interface: ParachainAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADAPTER_ADMIN: TypedContractMethod<[], [string], "view">;

  BRIDGE_OPERATOR: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addLiquidity: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  configureParachain: TypedContractMethod<
    [
      parachainId: BigNumberish,
      name: string,
      bridgeFee: BigNumberish,
      minTransfer: BigNumberish,
      maxTransfer: BigNumberish,
      timeout: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAdapterInfo: TypedContractMethod<
    [],
    [ILiquidityAdapter.AdapterInfoStructOutput],
    "view"
  >;

  getAmountOut: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        fee: bigint;
        priceImpact: bigint;
      }
    ],
    "view"
  >;

  getAssetId: TypedContractMethod<
    [token: AddressLike, parachainId: BigNumberish],
    [string],
    "view"
  >;

  getParachainConfig: TypedContractMethod<
    [parachainId: BigNumberish],
    [ParachainAdapter.ParachainConfigStructOutput],
    "view"
  >;

  getParachainTokens: TypedContractMethod<
    [parachainId: BigNumberish],
    [string[]],
    "view"
  >;

  getReserves: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { reserve: bigint; lastUpdate: bigint }],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSupportedParachains: TypedContractMethod<[], [bigint[]], "view">;

  getTokenMapping: TypedContractMethod<
    [token: AddressLike, parachainId: BigNumberish],
    [ParachainAdapter.TokenMappingStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isTokenSupported: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  mapToken: TypedContractMethod<
    [
      token: AddressLike,
      parachainId: BigNumberish,
      assetId: BytesLike,
      decimals: BigNumberish,
      minTransfer: BigNumberish,
      maxTransfer: BigNumberish,
      isNative: boolean
    ],
    [void],
    "nonpayable"
  >;

  removeLiquidity: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setActive: TypedContractMethod<[active: boolean], [void], "nonpayable">;

  setFee: TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;

  setSwapLimits: TypedContractMethod<
    [minAmount: BigNumberish, maxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setXCMExecutor: TypedContractMethod<
    [newExecutor: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  swapExactTokensForTokens: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      arg3: BigNumberish,
      recipient: AddressLike,
      data: BytesLike
    ],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "nonpayable"
  >;

  unmapToken: TypedContractMethod<
    [token: AddressLike, parachainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateParachainConfig: TypedContractMethod<
    [
      parachainId: BigNumberish,
      bridgeFee: BigNumberish,
      minTransfer: BigNumberish,
      maxTransfer: BigNumberish,
      timeout: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADAPTER_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BRIDGE_OPERATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureParachain"
  ): TypedContractMethod<
    [
      parachainId: BigNumberish,
      name: string,
      bridgeFee: BigNumberish,
      minTransfer: BigNumberish,
      maxTransfer: BigNumberish,
      timeout: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAdapterInfo"
  ): TypedContractMethod<
    [],
    [ILiquidityAdapter.AdapterInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        fee: bigint;
        priceImpact: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssetId"
  ): TypedContractMethod<
    [token: AddressLike, parachainId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParachainConfig"
  ): TypedContractMethod<
    [parachainId: BigNumberish],
    [ParachainAdapter.ParachainConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParachainTokens"
  ): TypedContractMethod<[parachainId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { reserve: bigint; lastUpdate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSupportedParachains"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTokenMapping"
  ): TypedContractMethod<
    [token: AddressLike, parachainId: BigNumberish],
    [ParachainAdapter.TokenMappingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mapToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      parachainId: BigNumberish,
      assetId: BytesLike,
      decimals: BigNumberish,
      minTransfer: BigNumberish,
      maxTransfer: BigNumberish,
      isNative: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, arg2: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<[active: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSwapLimits"
  ): TypedContractMethod<
    [minAmount: BigNumberish, maxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setXCMExecutor"
  ): TypedContractMethod<[newExecutor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapExactTokensForTokens"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      arg3: BigNumberish,
      recipient: AddressLike,
      data: BytesLike
    ],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unmapToken"
  ): TypedContractMethod<
    [token: AddressLike, parachainId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateParachainConfig"
  ): TypedContractMethod<
    [
      parachainId: BigNumberish,
      bridgeFee: BigNumberish,
      minTransfer: BigNumberish,
      maxTransfer: BigNumberish,
      timeout: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdapterActivated"
  ): TypedContractEvent<
    AdapterActivatedEvent.InputTuple,
    AdapterActivatedEvent.OutputTuple,
    AdapterActivatedEvent.OutputObject
  >;
  getEvent(
    key: "AdapterDeactivated"
  ): TypedContractEvent<
    AdapterDeactivatedEvent.InputTuple,
    AdapterDeactivatedEvent.OutputTuple,
    AdapterDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeExecuted"
  ): TypedContractEvent<
    BridgeExecutedEvent.InputTuple,
    BridgeExecutedEvent.OutputTuple,
    BridgeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ParachainConfigured"
  ): TypedContractEvent<
    ParachainConfiguredEvent.InputTuple,
    ParachainConfiguredEvent.OutputTuple,
    ParachainConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TokenMapped"
  ): TypedContractEvent<
    TokenMappedEvent.InputTuple,
    TokenMappedEvent.OutputTuple,
    TokenMappedEvent.OutputObject
  >;

  filters: {
    "AdapterActivated(address)": TypedContractEvent<
      AdapterActivatedEvent.InputTuple,
      AdapterActivatedEvent.OutputTuple,
      AdapterActivatedEvent.OutputObject
    >;
    AdapterActivated: TypedContractEvent<
      AdapterActivatedEvent.InputTuple,
      AdapterActivatedEvent.OutputTuple,
      AdapterActivatedEvent.OutputObject
    >;

    "AdapterDeactivated(address)": TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;
    AdapterDeactivated: TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;

    "BridgeExecuted(bytes32,uint32,address,uint256)": TypedContractEvent<
      BridgeExecutedEvent.InputTuple,
      BridgeExecutedEvent.OutputTuple,
      BridgeExecutedEvent.OutputObject
    >;
    BridgeExecuted: TypedContractEvent<
      BridgeExecutedEvent.InputTuple,
      BridgeExecutedEvent.OutputTuple,
      BridgeExecutedEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "ParachainConfigured(uint32,string,uint256)": TypedContractEvent<
      ParachainConfiguredEvent.InputTuple,
      ParachainConfiguredEvent.OutputTuple,
      ParachainConfiguredEvent.OutputObject
    >;
    ParachainConfigured: TypedContractEvent<
      ParachainConfiguredEvent.InputTuple,
      ParachainConfiguredEvent.OutputTuple,
      ParachainConfiguredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SwapExecuted(address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;

    "TokenMapped(address,uint32,bytes32)": TypedContractEvent<
      TokenMappedEvent.InputTuple,
      TokenMappedEvent.OutputTuple,
      TokenMappedEvent.OutputObject
    >;
    TokenMapped: TypedContractEvent<
      TokenMappedEvent.InputTuple,
      TokenMappedEvent.OutputTuple,
      TokenMappedEvent.OutputObject
    >;
  };
}
