/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IXcm {
  export type WeightStruct = { refTime: BigNumberish; proofSize: BigNumberish };

  export type WeightStructOutput = [refTime: bigint, proofSize: bigint] & {
    refTime: bigint;
    proofSize: bigint;
  };
}

export interface IXcmInterface extends Interface {
  getFunction(
    nameOrSignature: "weighMessage" | "xcmExecute" | "xcmSend"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "weighMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xcmExecute",
    values: [BytesLike, IXcm.WeightStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "xcmSend",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "weighMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xcmExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xcmSend", data: BytesLike): Result;
}

export interface IXcm extends BaseContract {
  connect(runner?: ContractRunner | null): IXcm;
  waitForDeployment(): Promise<this>;

  interface: IXcmInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  weighMessage: TypedContractMethod<
    [message: BytesLike],
    [IXcm.WeightStructOutput],
    "view"
  >;

  xcmExecute: TypedContractMethod<
    [message: BytesLike, weight: IXcm.WeightStruct],
    [void],
    "nonpayable"
  >;

  xcmSend: TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "weighMessage"
  ): TypedContractMethod<
    [message: BytesLike],
    [IXcm.WeightStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "xcmExecute"
  ): TypedContractMethod<
    [message: BytesLike, weight: IXcm.WeightStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xcmSend"
  ): TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
