/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ILiquidityAdapter {
  export type AdapterInfoStruct = {
    name: string;
    adapterAddress: AddressLike;
    isActive: boolean;
    tvl: BigNumberish;
    fee: BigNumberish;
    minSwapAmount: BigNumberish;
    maxSwapAmount: BigNumberish;
    supportedTokens: AddressLike[];
  };

  export type AdapterInfoStructOutput = [
    name: string,
    adapterAddress: string,
    isActive: boolean,
    tvl: bigint,
    fee: bigint,
    minSwapAmount: bigint,
    maxSwapAmount: bigint,
    supportedTokens: string[]
  ] & {
    name: string;
    adapterAddress: string;
    isActive: boolean;
    tvl: bigint;
    fee: bigint;
    minSwapAmount: bigint;
    maxSwapAmount: bigint;
    supportedTokens: string[];
  };
}

export interface ILiquidityAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAdapterInfo"
      | "getAmountOut"
      | "getReserves"
      | "isTokenSupported"
      | "swapExactTokensForTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterActivated"
      | "AdapterDeactivated"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "SwapExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAdapterInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokens",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAdapterInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokens",
    data: BytesLike
  ): Result;
}

export namespace AdapterActivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdapterDeactivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    newReserve: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, newReserve: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    newReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    newReserve: BigNumberish
  ];
  export type OutputTuple = [token: string, amount: bigint, newReserve: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
    newReserve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    adapter: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    adapter: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint,
    recipient: string
  ];
  export interface OutputObject {
    adapter: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILiquidityAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): ILiquidityAdapter;
  waitForDeployment(): Promise<this>;

  interface: ILiquidityAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAdapterInfo: TypedContractMethod<
    [],
    [ILiquidityAdapter.AdapterInfoStructOutput],
    "view"
  >;

  getAmountOut: TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        fee: bigint;
        priceImpact: bigint;
      }
    ],
    "view"
  >;

  getReserves: TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { reserve: bigint; lastUpdate: bigint }],
    "view"
  >;

  isTokenSupported: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  swapExactTokensForTokens: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      recipient: AddressLike,
      data: BytesLike
    ],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAdapterInfo"
  ): TypedContractMethod<
    [],
    [ILiquidityAdapter.AdapterInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        fee: bigint;
        priceImpact: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, bigint] & { reserve: bigint; lastUpdate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapExactTokensForTokens"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      recipient: AddressLike,
      data: BytesLike
    ],
    [[bigint, bigint] & { amountOut: bigint; fee: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "AdapterActivated"
  ): TypedContractEvent<
    AdapterActivatedEvent.InputTuple,
    AdapterActivatedEvent.OutputTuple,
    AdapterActivatedEvent.OutputObject
  >;
  getEvent(
    key: "AdapterDeactivated"
  ): TypedContractEvent<
    AdapterDeactivatedEvent.InputTuple,
    AdapterDeactivatedEvent.OutputTuple,
    AdapterDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;

  filters: {
    "AdapterActivated(address)": TypedContractEvent<
      AdapterActivatedEvent.InputTuple,
      AdapterActivatedEvent.OutputTuple,
      AdapterActivatedEvent.OutputObject
    >;
    AdapterActivated: TypedContractEvent<
      AdapterActivatedEvent.InputTuple,
      AdapterActivatedEvent.OutputTuple,
      AdapterActivatedEvent.OutputObject
    >;

    "AdapterDeactivated(address)": TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;
    AdapterDeactivated: TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "SwapExecuted(address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
  };
}
