/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IXcmPrecompile {
  export type WeightStruct = { refTime: BigNumberish; proofSize: BigNumberish };

  export type WeightStructOutput = [refTime: bigint, proofSize: bigint] & {
    refTime: bigint;
    proofSize: bigint;
  };
}

export declare namespace CrossChainExecutor {
  export type ChainConfigStruct = {
    chainId: BigNumberish;
    name: string;
    baseFee: BigNumberish;
    weightFee: BigNumberish;
    minFee: BigNumberish;
    maxWeight: BigNumberish;
    isActive: boolean;
    xcmRefTime: BigNumberish;
    xcmProofSize: BigNumberish;
  };

  export type ChainConfigStructOutput = [
    chainId: bigint,
    name: string,
    baseFee: bigint,
    weightFee: bigint,
    minFee: bigint,
    maxWeight: bigint,
    isActive: boolean,
    xcmRefTime: bigint,
    xcmProofSize: bigint
  ] & {
    chainId: bigint;
    name: string;
    baseFee: bigint;
    weightFee: bigint;
    minFee: bigint;
    maxWeight: bigint;
    isActive: boolean;
    xcmRefTime: bigint;
    xcmProofSize: bigint;
  };
}

export declare namespace IXCM {
  export type XCMMessageStruct = {
    id: BytesLike;
    sourceChainId: BigNumberish;
    destinationChainId: BigNumberish;
    sender: AddressLike;
    recipient: AddressLike;
    asset: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    timeout: BigNumberish;
    hash: BytesLike;
    status: BigNumberish;
  };

  export type XCMMessageStructOutput = [
    id: string,
    sourceChainId: bigint,
    destinationChainId: bigint,
    sender: string,
    recipient: string,
    asset: string,
    amount: bigint,
    timestamp: bigint,
    timeout: bigint,
    hash: string,
    status: bigint
  ] & {
    id: string;
    sourceChainId: bigint;
    destinationChainId: bigint;
    sender: string;
    recipient: string;
    asset: string;
    amount: bigint;
    timestamp: bigint;
    timeout: bigint;
    hash: string;
    status: bigint;
  };

  export type ParachainAssetStruct = {
    assetId: BytesLike;
    amount: BigNumberish;
    isNative: boolean;
  };

  export type ParachainAssetStructOutput = [
    assetId: string,
    amount: bigint,
    isNative: boolean
  ] & { assetId: string; amount: bigint; isNative: boolean };
}

export interface CrossChainExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONFIGURATOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "RELAYER_ROLE"
      | "XCM_PRECOMPILE"
      | "calculateFee"
      | "cancelMessage"
      | "configureChain"
      | "deactivateChain"
      | "estimateXCMWeight"
      | "getChainConfig"
      | "getMessageDetails"
      | "getMessageStatus"
      | "getNonce"
      | "getRoleAdmin"
      | "getTokenForAsset"
      | "grantRole"
      | "hasRole"
      | "mapAsset"
      | "markExecuted"
      | "processExpiredMessages"
      | "renounceRole"
      | "revokeRole"
      | "sendParachainAssets"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetMapped"
      | "ChainConfigured"
      | "ChainDeactivated"
      | "MessageStatusUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "XCMMessageCancelled"
      | "XCMMessageExecuted"
      | "XCMMessageExpired"
      | "XCMMessagePrepared"
      | "XCMSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CONFIGURATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XCM_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "configureChain",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateXCMWeight",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenForAsset",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mapAsset",
    values: [BigNumberish, BytesLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "markExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processExpiredMessages",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendParachainAssets",
    values: [
      BigNumberish,
      AddressLike,
      IXCM.ParachainAssetStruct[],
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CONFIGURATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XCM_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateXCMWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenForAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mapAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processExpiredMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendParachainAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace AssetMappedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    assetId: BytesLike,
    token: AddressLike,
    decimals: BigNumberish,
    isNative: boolean
  ];
  export type OutputTuple = [
    chainId: bigint,
    assetId: string,
    token: string,
    decimals: bigint,
    isNative: boolean
  ];
  export interface OutputObject {
    chainId: bigint;
    assetId: string;
    token: string;
    decimals: bigint;
    isNative: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainConfiguredEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    name: string,
    baseFee: BigNumberish
  ];
  export type OutputTuple = [chainId: bigint, name: string, baseFee: bigint];
  export interface OutputObject {
    chainId: bigint;
    name: string;
    baseFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainDeactivatedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageStatusUpdatedEvent {
  export type InputTuple = [messageId: BytesLike, status: BigNumberish];
  export type OutputTuple = [messageId: string, status: bigint];
  export interface OutputObject {
    messageId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageCancelledEvent {
  export type InputTuple = [messageId: BytesLike];
  export type OutputTuple = [messageId: string];
  export interface OutputObject {
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageExecutedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    xcmHash: BytesLike,
    success: boolean
  ];
  export type OutputTuple = [
    messageId: string,
    xcmHash: string,
    success: boolean
  ];
  export interface OutputObject {
    messageId: string;
    xcmHash: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageExpiredEvent {
  export type InputTuple = [messageId: BytesLike];
  export type OutputTuple = [messageId: string];
  export interface OutputObject {
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessagePreparedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    destinationChainId: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    timeout: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    destinationChainId: bigint,
    sender: string,
    recipient: string,
    asset: string,
    amount: bigint,
    timeout: bigint
  ];
  export interface OutputObject {
    messageId: string;
    destinationChainId: bigint;
    sender: string;
    recipient: string;
    asset: string;
    amount: bigint;
    timeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMSentEvent {
  export type InputTuple = [
    messageId: BytesLike,
    destination: BytesLike,
    xcmMessage: BytesLike
  ];
  export type OutputTuple = [
    messageId: string,
    destination: string,
    xcmMessage: string
  ];
  export interface OutputObject {
    messageId: string;
    destination: string;
    xcmMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainExecutor;
  waitForDeployment(): Promise<this>;

  interface: CrossChainExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONFIGURATOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  XCM_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  calculateFee: TypedContractMethod<
    [chainId: BigNumberish, weight: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  cancelMessage: TypedContractMethod<
    [messageId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  configureChain: TypedContractMethod<
    [
      chainId: BigNumberish,
      name: string,
      baseFee: BigNumberish,
      weightFee: BigNumberish,
      minFee: BigNumberish,
      maxWeight: BigNumberish,
      xcmRefTime: BigNumberish,
      xcmProofSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  deactivateChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  estimateXCMWeight: TypedContractMethod<
    [parachainId: BigNumberish, amount: BigNumberish],
    [IXcmPrecompile.WeightStructOutput],
    "view"
  >;

  getChainConfig: TypedContractMethod<
    [chainId: BigNumberish],
    [CrossChainExecutor.ChainConfigStructOutput],
    "view"
  >;

  getMessageDetails: TypedContractMethod<
    [messageId: BytesLike],
    [IXCM.XCMMessageStructOutput],
    "view"
  >;

  getMessageStatus: TypedContractMethod<
    [messageId: BytesLike],
    [bigint],
    "view"
  >;

  getNonce: TypedContractMethod<
    [sender: AddressLike, chainId: BigNumberish],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTokenForAsset: TypedContractMethod<
    [chainId: BigNumberish, assetId: BytesLike],
    [string],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  mapAsset: TypedContractMethod<
    [
      chainId: BigNumberish,
      assetId: BytesLike,
      tokenAddress: AddressLike,
      decimals: BigNumberish,
      isNative: boolean
    ],
    [void],
    "nonpayable"
  >;

  markExecuted: TypedContractMethod<
    [messageId: BytesLike],
    [void],
    "nonpayable"
  >;

  processExpiredMessages: TypedContractMethod<
    [ids: BytesLike[]],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sendParachainAssets: TypedContractMethod<
    [
      parachainId: BigNumberish,
      recipient: AddressLike,
      assets: IXCM.ParachainAssetStruct[],
      arg3: BytesLike,
      timeout: BigNumberish
    ],
    [string],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONFIGURATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "XCM_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateFee"
  ): TypedContractMethod<
    [chainId: BigNumberish, weight: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelMessage"
  ): TypedContractMethod<[messageId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "configureChain"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      name: string,
      baseFee: BigNumberish,
      weightFee: BigNumberish,
      minFee: BigNumberish,
      maxWeight: BigNumberish,
      xcmRefTime: BigNumberish,
      xcmProofSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "estimateXCMWeight"
  ): TypedContractMethod<
    [parachainId: BigNumberish, amount: BigNumberish],
    [IXcmPrecompile.WeightStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChainConfig"
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [CrossChainExecutor.ChainConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageDetails"
  ): TypedContractMethod<
    [messageId: BytesLike],
    [IXCM.XCMMessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageStatus"
  ): TypedContractMethod<[messageId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<
    [sender: AddressLike, chainId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenForAsset"
  ): TypedContractMethod<
    [chainId: BigNumberish, assetId: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mapAsset"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      assetId: BytesLike,
      tokenAddress: AddressLike,
      decimals: BigNumberish,
      isNative: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markExecuted"
  ): TypedContractMethod<[messageId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "processExpiredMessages"
  ): TypedContractMethod<[ids: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendParachainAssets"
  ): TypedContractMethod<
    [
      parachainId: BigNumberish,
      recipient: AddressLike,
      assets: IXCM.ParachainAssetStruct[],
      arg3: BytesLike,
      timeout: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "AssetMapped"
  ): TypedContractEvent<
    AssetMappedEvent.InputTuple,
    AssetMappedEvent.OutputTuple,
    AssetMappedEvent.OutputObject
  >;
  getEvent(
    key: "ChainConfigured"
  ): TypedContractEvent<
    ChainConfiguredEvent.InputTuple,
    ChainConfiguredEvent.OutputTuple,
    ChainConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "ChainDeactivated"
  ): TypedContractEvent<
    ChainDeactivatedEvent.InputTuple,
    ChainDeactivatedEvent.OutputTuple,
    ChainDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MessageStatusUpdated"
  ): TypedContractEvent<
    MessageStatusUpdatedEvent.InputTuple,
    MessageStatusUpdatedEvent.OutputTuple,
    MessageStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageCancelled"
  ): TypedContractEvent<
    XCMMessageCancelledEvent.InputTuple,
    XCMMessageCancelledEvent.OutputTuple,
    XCMMessageCancelledEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageExecuted"
  ): TypedContractEvent<
    XCMMessageExecutedEvent.InputTuple,
    XCMMessageExecutedEvent.OutputTuple,
    XCMMessageExecutedEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageExpired"
  ): TypedContractEvent<
    XCMMessageExpiredEvent.InputTuple,
    XCMMessageExpiredEvent.OutputTuple,
    XCMMessageExpiredEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessagePrepared"
  ): TypedContractEvent<
    XCMMessagePreparedEvent.InputTuple,
    XCMMessagePreparedEvent.OutputTuple,
    XCMMessagePreparedEvent.OutputObject
  >;
  getEvent(
    key: "XCMSent"
  ): TypedContractEvent<
    XCMSentEvent.InputTuple,
    XCMSentEvent.OutputTuple,
    XCMSentEvent.OutputObject
  >;

  filters: {
    "AssetMapped(uint32,bytes32,address,uint8,bool)": TypedContractEvent<
      AssetMappedEvent.InputTuple,
      AssetMappedEvent.OutputTuple,
      AssetMappedEvent.OutputObject
    >;
    AssetMapped: TypedContractEvent<
      AssetMappedEvent.InputTuple,
      AssetMappedEvent.OutputTuple,
      AssetMappedEvent.OutputObject
    >;

    "ChainConfigured(uint32,string,uint256)": TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;
    ChainConfigured: TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;

    "ChainDeactivated(uint32)": TypedContractEvent<
      ChainDeactivatedEvent.InputTuple,
      ChainDeactivatedEvent.OutputTuple,
      ChainDeactivatedEvent.OutputObject
    >;
    ChainDeactivated: TypedContractEvent<
      ChainDeactivatedEvent.InputTuple,
      ChainDeactivatedEvent.OutputTuple,
      ChainDeactivatedEvent.OutputObject
    >;

    "MessageStatusUpdated(bytes32,uint8)": TypedContractEvent<
      MessageStatusUpdatedEvent.InputTuple,
      MessageStatusUpdatedEvent.OutputTuple,
      MessageStatusUpdatedEvent.OutputObject
    >;
    MessageStatusUpdated: TypedContractEvent<
      MessageStatusUpdatedEvent.InputTuple,
      MessageStatusUpdatedEvent.OutputTuple,
      MessageStatusUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "XCMMessageCancelled(bytes32)": TypedContractEvent<
      XCMMessageCancelledEvent.InputTuple,
      XCMMessageCancelledEvent.OutputTuple,
      XCMMessageCancelledEvent.OutputObject
    >;
    XCMMessageCancelled: TypedContractEvent<
      XCMMessageCancelledEvent.InputTuple,
      XCMMessageCancelledEvent.OutputTuple,
      XCMMessageCancelledEvent.OutputObject
    >;

    "XCMMessageExecuted(bytes32,bytes32,bool)": TypedContractEvent<
      XCMMessageExecutedEvent.InputTuple,
      XCMMessageExecutedEvent.OutputTuple,
      XCMMessageExecutedEvent.OutputObject
    >;
    XCMMessageExecuted: TypedContractEvent<
      XCMMessageExecutedEvent.InputTuple,
      XCMMessageExecutedEvent.OutputTuple,
      XCMMessageExecutedEvent.OutputObject
    >;

    "XCMMessageExpired(bytes32)": TypedContractEvent<
      XCMMessageExpiredEvent.InputTuple,
      XCMMessageExpiredEvent.OutputTuple,
      XCMMessageExpiredEvent.OutputObject
    >;
    XCMMessageExpired: TypedContractEvent<
      XCMMessageExpiredEvent.InputTuple,
      XCMMessageExpiredEvent.OutputTuple,
      XCMMessageExpiredEvent.OutputObject
    >;

    "XCMMessagePrepared(bytes32,uint32,address,address,address,uint128,uint64)": TypedContractEvent<
      XCMMessagePreparedEvent.InputTuple,
      XCMMessagePreparedEvent.OutputTuple,
      XCMMessagePreparedEvent.OutputObject
    >;
    XCMMessagePrepared: TypedContractEvent<
      XCMMessagePreparedEvent.InputTuple,
      XCMMessagePreparedEvent.OutputTuple,
      XCMMessagePreparedEvent.OutputObject
    >;

    "XCMSent(bytes32,bytes,bytes)": TypedContractEvent<
      XCMSentEvent.InputTuple,
      XCMSentEvent.OutputTuple,
      XCMSentEvent.OutputObject
    >;
    XCMSent: TypedContractEvent<
      XCMSentEvent.InputTuple,
      XCMSentEvent.OutputTuple,
      XCMSentEvent.OutputObject
    >;
  };
}
