/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CrossChainExecutor {
  export type ChainConfigStruct = {
    chainId: BigNumberish;
    name: string;
    baseFee: BigNumberish;
    weightFee: BigNumberish;
    minFee: BigNumberish;
    maxWeight: BigNumberish;
    gateway: AddressLike;
    genesisHash: BytesLike;
    isActive: boolean;
  };

  export type ChainConfigStructOutput = [
    chainId: bigint,
    name: string,
    baseFee: bigint,
    weightFee: bigint,
    minFee: bigint,
    maxWeight: bigint,
    gateway: string,
    genesisHash: string,
    isActive: boolean
  ] & {
    chainId: bigint;
    name: string;
    baseFee: bigint;
    weightFee: bigint;
    minFee: bigint;
    maxWeight: bigint;
    gateway: string;
    genesisHash: string;
    isActive: boolean;
  };
}

export declare namespace IXCM {
  export type XCMMessageStruct = {
    id: BytesLike;
    sourceChainId: BigNumberish;
    destinationChainId: BigNumberish;
    sender: AddressLike;
    recipient: AddressLike;
    asset: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    timeout: BigNumberish;
    hash: BytesLike;
    status: BigNumberish;
  };

  export type XCMMessageStructOutput = [
    id: string,
    sourceChainId: bigint,
    destinationChainId: bigint,
    sender: string,
    recipient: string,
    asset: string,
    amount: bigint,
    timestamp: bigint,
    timeout: bigint,
    hash: string,
    status: bigint
  ] & {
    id: string;
    sourceChainId: bigint;
    destinationChainId: bigint;
    sender: string;
    recipient: string;
    asset: string;
    amount: bigint;
    timestamp: bigint;
    timeout: bigint;
    hash: string;
    status: bigint;
  };

  export type ParachainAssetStruct = {
    assetId: BytesLike;
    amount: BigNumberish;
    isNative: boolean;
  };

  export type ParachainAssetStructOutput = [
    assetId: string,
    amount: bigint,
    isNative: boolean
  ] & { assetId: string; amount: bigint; isNative: boolean };

  export type XCMInstructionStruct = {
    destinationChainId: BigNumberish;
    sender: AddressLike;
    recipient: AddressLike;
    asset: AddressLike;
    amount: BigNumberish;
    callData: BytesLike;
    weight: BigNumberish;
    transactWeight: BigNumberish;
    timeout: BigNumberish;
  };

  export type XCMInstructionStructOutput = [
    destinationChainId: bigint,
    sender: string,
    recipient: string,
    asset: string,
    amount: bigint,
    callData: string,
    weight: bigint,
    transactWeight: bigint,
    timeout: bigint
  ] & {
    destinationChainId: bigint;
    sender: string;
    recipient: string;
    asset: string;
    amount: bigint;
    callData: string;
    weight: bigint;
    transactWeight: bigint;
    timeout: bigint;
  };
}

export interface CrossChainExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CONFIGURATOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "RELAYER_ROLE"
      | "calculateFee"
      | "cancelMessage"
      | "configureChain"
      | "deactivateChain"
      | "eip712Domain"
      | "executeXCM"
      | "getChainConfig"
      | "getMessageDetails"
      | "getMessageStatus"
      | "getNonce"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "processExpiredMessages"
      | "renounceRole"
      | "revokeRole"
      | "sendParachainAssets"
      | "sendXCM"
      | "supportsInterface"
      | "verifyXCM"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainConfigured"
      | "ChainDeactivated"
      | "EIP712DomainChanged"
      | "MessageStatusUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "XCMMessageCancelled"
      | "XCMMessageExecuted"
      | "XCMMessageExpired"
      | "XCMMessageFailed"
      | "XCMMessagePrepared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CONFIGURATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "configureChain",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeXCM",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainConfig",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processExpiredMessages",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendParachainAssets",
    values: [
      BigNumberish,
      AddressLike,
      IXCM.ParachainAssetStruct[],
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendXCM",
    values: [IXCM.XCMInstructionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyXCM",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CONFIGURATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executeXCM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChainConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processExpiredMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendParachainAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendXCM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyXCM", data: BytesLike): Result;
}

export namespace ChainConfiguredEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    name: string,
    gateway: AddressLike,
    baseFee: BigNumberish
  ];
  export type OutputTuple = [
    chainId: bigint,
    name: string,
    gateway: string,
    baseFee: bigint
  ];
  export interface OutputObject {
    chainId: bigint;
    name: string;
    gateway: string;
    baseFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainDeactivatedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageStatusUpdatedEvent {
  export type InputTuple = [messageId: BytesLike, status: BigNumberish];
  export type OutputTuple = [messageId: string, status: bigint];
  export interface OutputObject {
    messageId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageCancelledEvent {
  export type InputTuple = [messageId: BytesLike];
  export type OutputTuple = [messageId: string];
  export interface OutputObject {
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageExecutedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    transactionHash: BytesLike,
    success: boolean
  ];
  export type OutputTuple = [
    messageId: string,
    transactionHash: string,
    success: boolean
  ];
  export interface OutputObject {
    messageId: string;
    transactionHash: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageExpiredEvent {
  export type InputTuple = [messageId: BytesLike];
  export type OutputTuple = [messageId: string];
  export interface OutputObject {
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessageFailedEvent {
  export type InputTuple = [messageId: BytesLike, reason: BytesLike];
  export type OutputTuple = [messageId: string, reason: string];
  export interface OutputObject {
    messageId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XCMMessagePreparedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    destinationChainId: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    timeout: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    destinationChainId: bigint,
    sender: string,
    recipient: string,
    asset: string,
    amount: bigint,
    timeout: bigint
  ];
  export interface OutputObject {
    messageId: string;
    destinationChainId: bigint;
    sender: string;
    recipient: string;
    asset: string;
    amount: bigint;
    timeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainExecutor;
  waitForDeployment(): Promise<this>;

  interface: CrossChainExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CONFIGURATOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  calculateFee: TypedContractMethod<
    [
      destinationChainId: BigNumberish,
      weight: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  cancelMessage: TypedContractMethod<
    [messageId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  configureChain: TypedContractMethod<
    [
      chainId: BigNumberish,
      name: string,
      baseFee: BigNumberish,
      weightFee: BigNumberish,
      minFee: BigNumberish,
      maxWeight: BigNumberish,
      gateway: AddressLike,
      genesisHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  deactivateChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  executeXCM: TypedContractMethod<
    [encodedMessage: BytesLike, signature: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;

  getChainConfig: TypedContractMethod<
    [chainId: BigNumberish],
    [CrossChainExecutor.ChainConfigStructOutput],
    "view"
  >;

  getMessageDetails: TypedContractMethod<
    [messageId: BytesLike],
    [IXCM.XCMMessageStructOutput],
    "view"
  >;

  getMessageStatus: TypedContractMethod<
    [messageId: BytesLike],
    [bigint],
    "view"
  >;

  getNonce: TypedContractMethod<
    [sender: AddressLike, destinationChainId: BigNumberish],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  processExpiredMessages: TypedContractMethod<
    [messageIds: BytesLike[]],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sendParachainAssets: TypedContractMethod<
    [
      parachainId: BigNumberish,
      recipient: AddressLike,
      assets: IXCM.ParachainAssetStruct[],
      callData: BytesLike,
      timeout: BigNumberish
    ],
    [string],
    "payable"
  >;

  sendXCM: TypedContractMethod<
    [instruction: IXCM.XCMInstructionStruct],
    [string],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifyXCM: TypedContractMethod<
    [messageId: BytesLike, proof: BytesLike],
    [[boolean, string] & { isValid: boolean; decodedMessage: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CONFIGURATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateFee"
  ): TypedContractMethod<
    [
      destinationChainId: BigNumberish,
      weight: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelMessage"
  ): TypedContractMethod<[messageId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "configureChain"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      name: string,
      baseFee: BigNumberish,
      weightFee: BigNumberish,
      minFee: BigNumberish,
      maxWeight: BigNumberish,
      gateway: AddressLike,
      genesisHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeXCM"
  ): TypedContractMethod<
    [encodedMessage: BytesLike, signature: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getChainConfig"
  ): TypedContractMethod<
    [chainId: BigNumberish],
    [CrossChainExecutor.ChainConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageDetails"
  ): TypedContractMethod<
    [messageId: BytesLike],
    [IXCM.XCMMessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageStatus"
  ): TypedContractMethod<[messageId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<
    [sender: AddressLike, destinationChainId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "processExpiredMessages"
  ): TypedContractMethod<[messageIds: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendParachainAssets"
  ): TypedContractMethod<
    [
      parachainId: BigNumberish,
      recipient: AddressLike,
      assets: IXCM.ParachainAssetStruct[],
      callData: BytesLike,
      timeout: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sendXCM"
  ): TypedContractMethod<
    [instruction: IXCM.XCMInstructionStruct],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyXCM"
  ): TypedContractMethod<
    [messageId: BytesLike, proof: BytesLike],
    [[boolean, string] & { isValid: boolean; decodedMessage: string }],
    "view"
  >;

  getEvent(
    key: "ChainConfigured"
  ): TypedContractEvent<
    ChainConfiguredEvent.InputTuple,
    ChainConfiguredEvent.OutputTuple,
    ChainConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "ChainDeactivated"
  ): TypedContractEvent<
    ChainDeactivatedEvent.InputTuple,
    ChainDeactivatedEvent.OutputTuple,
    ChainDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "MessageStatusUpdated"
  ): TypedContractEvent<
    MessageStatusUpdatedEvent.InputTuple,
    MessageStatusUpdatedEvent.OutputTuple,
    MessageStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageCancelled"
  ): TypedContractEvent<
    XCMMessageCancelledEvent.InputTuple,
    XCMMessageCancelledEvent.OutputTuple,
    XCMMessageCancelledEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageExecuted"
  ): TypedContractEvent<
    XCMMessageExecutedEvent.InputTuple,
    XCMMessageExecutedEvent.OutputTuple,
    XCMMessageExecutedEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageExpired"
  ): TypedContractEvent<
    XCMMessageExpiredEvent.InputTuple,
    XCMMessageExpiredEvent.OutputTuple,
    XCMMessageExpiredEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessageFailed"
  ): TypedContractEvent<
    XCMMessageFailedEvent.InputTuple,
    XCMMessageFailedEvent.OutputTuple,
    XCMMessageFailedEvent.OutputObject
  >;
  getEvent(
    key: "XCMMessagePrepared"
  ): TypedContractEvent<
    XCMMessagePreparedEvent.InputTuple,
    XCMMessagePreparedEvent.OutputTuple,
    XCMMessagePreparedEvent.OutputObject
  >;

  filters: {
    "ChainConfigured(uint32,string,address,uint256)": TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;
    ChainConfigured: TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;

    "ChainDeactivated(uint32)": TypedContractEvent<
      ChainDeactivatedEvent.InputTuple,
      ChainDeactivatedEvent.OutputTuple,
      ChainDeactivatedEvent.OutputObject
    >;
    ChainDeactivated: TypedContractEvent<
      ChainDeactivatedEvent.InputTuple,
      ChainDeactivatedEvent.OutputTuple,
      ChainDeactivatedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "MessageStatusUpdated(bytes32,uint8)": TypedContractEvent<
      MessageStatusUpdatedEvent.InputTuple,
      MessageStatusUpdatedEvent.OutputTuple,
      MessageStatusUpdatedEvent.OutputObject
    >;
    MessageStatusUpdated: TypedContractEvent<
      MessageStatusUpdatedEvent.InputTuple,
      MessageStatusUpdatedEvent.OutputTuple,
      MessageStatusUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "XCMMessageCancelled(bytes32)": TypedContractEvent<
      XCMMessageCancelledEvent.InputTuple,
      XCMMessageCancelledEvent.OutputTuple,
      XCMMessageCancelledEvent.OutputObject
    >;
    XCMMessageCancelled: TypedContractEvent<
      XCMMessageCancelledEvent.InputTuple,
      XCMMessageCancelledEvent.OutputTuple,
      XCMMessageCancelledEvent.OutputObject
    >;

    "XCMMessageExecuted(bytes32,bytes32,bool)": TypedContractEvent<
      XCMMessageExecutedEvent.InputTuple,
      XCMMessageExecutedEvent.OutputTuple,
      XCMMessageExecutedEvent.OutputObject
    >;
    XCMMessageExecuted: TypedContractEvent<
      XCMMessageExecutedEvent.InputTuple,
      XCMMessageExecutedEvent.OutputTuple,
      XCMMessageExecutedEvent.OutputObject
    >;

    "XCMMessageExpired(bytes32)": TypedContractEvent<
      XCMMessageExpiredEvent.InputTuple,
      XCMMessageExpiredEvent.OutputTuple,
      XCMMessageExpiredEvent.OutputObject
    >;
    XCMMessageExpired: TypedContractEvent<
      XCMMessageExpiredEvent.InputTuple,
      XCMMessageExpiredEvent.OutputTuple,
      XCMMessageExpiredEvent.OutputObject
    >;

    "XCMMessageFailed(bytes32,bytes)": TypedContractEvent<
      XCMMessageFailedEvent.InputTuple,
      XCMMessageFailedEvent.OutputTuple,
      XCMMessageFailedEvent.OutputObject
    >;
    XCMMessageFailed: TypedContractEvent<
      XCMMessageFailedEvent.InputTuple,
      XCMMessageFailedEvent.OutputTuple,
      XCMMessageFailedEvent.OutputObject
    >;

    "XCMMessagePrepared(bytes32,uint32,address,address,address,uint256,uint64)": TypedContractEvent<
      XCMMessagePreparedEvent.InputTuple,
      XCMMessagePreparedEvent.OutputTuple,
      XCMMessagePreparedEvent.OutputObject
    >;
    XCMMessagePrepared: TypedContractEvent<
      XCMMessagePreparedEvent.InputTuple,
      XCMMessagePreparedEvent.OutputTuple,
      XCMMessagePreparedEvent.OutputObject
    >;
  };
}
