/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockUniswapV2Sol from "./MockUniswapV2.sol";
export type { mockUniswapV2Sol };
export type { MockERC20 } from "./MockERC20";
export type { MockXcmPrecompile } from "./MockXcmPrecompile";
