/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MockXcmPrecompile {
  export type WeightStruct = { refTime: BigNumberish; proofSize: BigNumberish };

  export type WeightStructOutput = [refTime: bigint, proofSize: bigint] & {
    refTime: bigint;
    proofSize: bigint;
  };
}

export interface MockXcmPrecompileInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lastSend"
      | "sendCallCount"
      | "setShouldRevert"
      | "shouldRevert"
      | "weighMessage"
      | "xcmExecute"
      | "xcmSend"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "lastSend", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setShouldRevert",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldRevert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "weighMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xcmExecute",
    values: [BytesLike, MockXcmPrecompile.WeightStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "xcmSend",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "lastSend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShouldRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weighMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xcmExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xcmSend", data: BytesLike): Result;
}

export interface MockXcmPrecompile extends BaseContract {
  connect(runner?: ContractRunner | null): MockXcmPrecompile;
  waitForDeployment(): Promise<this>;

  interface: MockXcmPrecompileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lastSend: TypedContractMethod<
    [],
    [[string, string] & { destination: string; message: string }],
    "view"
  >;

  sendCallCount: TypedContractMethod<[], [bigint], "view">;

  setShouldRevert: TypedContractMethod<
    [_revert: boolean],
    [void],
    "nonpayable"
  >;

  shouldRevert: TypedContractMethod<[], [boolean], "view">;

  weighMessage: TypedContractMethod<
    [arg0: BytesLike],
    [MockXcmPrecompile.WeightStructOutput],
    "view"
  >;

  xcmExecute: TypedContractMethod<
    [arg0: BytesLike, arg1: MockXcmPrecompile.WeightStruct],
    [void],
    "view"
  >;

  xcmSend: TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lastSend"
  ): TypedContractMethod<
    [],
    [[string, string] & { destination: string; message: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "sendCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setShouldRevert"
  ): TypedContractMethod<[_revert: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shouldRevert"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "weighMessage"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [MockXcmPrecompile.WeightStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "xcmExecute"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: MockXcmPrecompile.WeightStruct],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "xcmSend"
  ): TypedContractMethod<
    [destination: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
